### ISSUE TITLE
libcc_client.so: undefined reference to `json_*' when compiling mod-host

### ISSUE THREAD

**Issue by MaxPayne86** [moddevices/cc-master#3]
Hi,

it seems that libcc_client library is using methods from **json** library but is not linked correctly. Please compare with server **wscript**.
I've solved this problem by modifying client/wscript with

bld.shlib(source=source_files, target=APPNAME, use='CC CONTROLCHAIN JANSSON')

However after this I'm still getting other errors and I cannot build mod-host with this library at the moment. The other errors are

**libcc_client.so: undefined reference to `cc_update_free'**

Any thoughts?

[solved] on my side see https://github.com/moddevices/cc-master/pull/4

**Comment by falkTX** [comment]
Fixed by #4
